wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.40.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714684335.0
    t:
      1:
      - 1
      - 5
      - 11
      - 33
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      - 75
      - 100
      2:
      - 1
      - 5
      - 11
      - 33
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      - 75
      - 100
      3:
      - 13
      - 23
      - 61
      4: 3.10.12
      5: 0.16.6
      6: 4.40.0
      8:
      - 5
      13: linux-x86_64
dataset_name:
  desc: null
  value: roc
save_dir:
  desc: null
  value: saved_consistency_models
output_dir:
  desc: null
  value: saved_consistency_models/roc/2024-05-02_21-12-14
wandb_name:
  desc: null
  value: bart_consistency
optimizer:
  desc: null
  value: adamw
train_batch_size:
  desc: null
  value: 64
eval_batch_size:
  desc: null
  value: 32
num_train_steps:
  desc: null
  value: 250000
gradient_accumulation_steps:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 0.0002
clip_grad_norm:
  desc: null
  value: 1.0
lr_schedule:
  desc: null
  value: cosine
lr_warmup_steps:
  desc: null
  value: 1000
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_weight_decay:
  desc: null
  value: 1.0e-06
ema_decay:
  desc: null
  value: 0.9999
ema_update_every:
  desc: null
  value: 1
objective:
  desc: null
  value: pred_v
loss_type:
  desc: null
  value: l2
train_schedule:
  desc: null
  value: cosine
sampling_schedule:
  desc: null
  value: null
scale:
  desc: null
  value: 1.0
sampling_timesteps:
  desc: null
  value: 250
normalize_latent:
  desc: null
  value: false
save_and_sample_every:
  desc: null
  value: 2500
num_samples:
  desc: null
  value: 1000
seq2seq_candidates:
  desc: null
  value: 5
max_seq_len:
  desc: null
  value: 64
self_condition:
  desc: null
  value: true
train_prob_self_cond:
  desc: null
  value: 0.5
sampler:
  desc: null
  value: ddpm
enc_dec_model:
  desc: null
  value: facebook/bart-base
tx_dim:
  desc: null
  value: 768
tx_depth:
  desc: null
  value: 12
scale_shift:
  desc: null
  value: true
num_dense_connections:
  desc: null
  value: 3
disable_dropout:
  desc: null
  value: false
class_conditional:
  desc: null
  value: false
class_unconditional_prob:
  desc: null
  value: 0.1
seq2seq_unconditional_prob:
  desc: null
  value: 0.1
amp:
  desc: null
  value: false
mixed_precision:
  desc: null
  value: 'no'
eval:
  desc: null
  value: false
eval_test:
  desc: null
  value: false
resume_training:
  desc: null
  value: false
resume_dir:
  desc: null
  value: null
latent_model_path:
  desc: null
  value: saved_latent_models/roc/2024-04-22_08-22-55
init_path:
  desc: null
  value: null
device:
  desc: null
  value: cuda
init_models:
  desc: null
  value: true
diffusion_model_path:
  desc: null
  value: saved_diff_models/roc/2024-04-23_19-09-33
trainable_params:
  desc: null
  value: 187928960
num_devices:
  desc: null
  value: 1
